module.exports = {
  Canvas: require('./dist/canvas'),
  Group: require('./dist/core/group'),
  Shape: require('./dist/core/shape'),
  Rect: require('./dist/shape/rect'),
  Circle: require('./dist/shape/circle'),
  Ellipse: require('./dist/shape/ellipse'),
  Path: require('./dist/shape/path'),
  Text: require('./dist/shape/text'),
  Line: require('./dist/shape/line'),
  Image: require('./dist/shape/image'),
  Polygon: require('./dist/shape/polygon'),
  Polyline: require('./dist/shape/polyline'),
  Arc: require('./dist/shape/arc'),
  Fan: require('./dist/shape/fan'),
  Cubic: require('./dist/shape/cubic'),
  Quadratic: require('./dist/shape/quadratic'),
  Marker: require('./dist/shape/marker'),
  PathUtil: require('./dist/util/path'),
  MatrixUtil: require('./dist/util/matrix'),
  DomUtil: require('./dist/util/dom'),
  Event: require('./dist/event')
};
